# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 (no cache)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: none  # DISABLE internal cache to avoid v2

      - name: Setup Maven environment (with cache v4)
        uses: s4u/setup-maven-action@v1.15.0
        with:
          maven-version: '3.9.9'
          cache-enabled: true
          # s4u action manages checkout, Java, cache (v4), mvn tooling

      # Optional manual cache fallback
      - name: Cache Maven local repo
        uses: actions/cache@v4
        with:
          path: ${{ runner.os == 'Windows' && format('{0}\\.m2\\repository', env.USERPROFILE) || '~/.m2/repository' }}
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Submit dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6


